<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection') ?>
    </p>
<?php else: ?>
    <div class="category-products">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i = 0; foreach($_productCollection as $_product): ?>
            <?php if($i++%$_productCollection == 0): ?>
            <ul class="products-grid row">
            <?php endif; ?>
            </ul>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
