<div class="block block-subscribe">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="input-group">
            <span class="input-group-addon"><?php echo $this->__('Newsletter'); ?></span>
            <input type="text" class="form-control input-sm required-entry validate-email" title="<?php echo $this->__('Sign up for our news letter'); ?>" id="newsletter" name="email">
            <span class="input-group-btn">
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="btn btn-default btn-sm"><?php echo $this->__('Subscribe') ?></button>
            </span>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
