<div class="row">
    <div class="col-md-4">
        <?php echo $this->getChildHtml('footer-company'); ?>
    </div>
    <div class="col-md-8">
        <?php echo $this->getChildHtml('footer-cmslinks'); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <?php echo $this->getChildHtml('footer-newsletter'); ?>
    </div>
    <div class="col-md-6">
        <?php echo $this->getChildHtml('footer_newsletter') ?>
        <?php echo $this->getChildHtml('footer-social'); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12"></div>
    <hr/>
    <div class="col-md-8">
        <?php echo $this->getCopyright()?>
    </div>
    <div class="col-md-4">
        <?php echo $this->getChildHtml('footer-cards') ?>
    </div>
</div>

